[package]
name = "p2pio-contract"
version = "0.1.0"
authors = ["Colin Moore <colin@moore.one>"]
edition = "2018"

[lib]
name = "p2pio_contract"
crate-type = ["cdylib", "rlib"]

[dependencies]
rustdag_wasm_api = { path = "../rustdag/wasm_api" }
wasm-bindgen = "0.2.60"
